/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessPropertyRouteImport } from './routes/assess/property'
import { Route as AssessChecklistRouteImport } from './routes/assess/checklist'
import { Route as AssessAnalyzeRouteImport } from './routes/assess/analyze'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessPropertyRoute = AssessPropertyRouteImport.update({
  id: '/assess/property',
  path: '/assess/property',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessChecklistRoute = AssessChecklistRouteImport.update({
  id: '/assess/checklist',
  path: '/assess/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessAnalyzeRoute = AssessAnalyzeRouteImport.update({
  id: '/assess/analyze',
  path: '/assess/analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assess/analyze': typeof AssessAnalyzeRoute
  '/assess/checklist': typeof AssessChecklistRoute
  '/assess/property': typeof AssessPropertyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assess/analyze': typeof AssessAnalyzeRoute
  '/assess/checklist': typeof AssessChecklistRoute
  '/assess/property': typeof AssessPropertyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assess/analyze': typeof AssessAnalyzeRoute
  '/assess/checklist': typeof AssessChecklistRoute
  '/assess/property': typeof AssessPropertyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assess/analyze' | '/assess/checklist' | '/assess/property'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assess/analyze' | '/assess/checklist' | '/assess/property'
  id:
    | '__root__'
    | '/'
    | '/assess/analyze'
    | '/assess/checklist'
    | '/assess/property'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessAnalyzeRoute: typeof AssessAnalyzeRoute
  AssessChecklistRoute: typeof AssessChecklistRoute
  AssessPropertyRoute: typeof AssessPropertyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/property': {
      id: '/assess/property'
      path: '/assess/property'
      fullPath: '/assess/property'
      preLoaderRoute: typeof AssessPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/checklist': {
      id: '/assess/checklist'
      path: '/assess/checklist'
      fullPath: '/assess/checklist'
      preLoaderRoute: typeof AssessChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/analyze': {
      id: '/assess/analyze'
      path: '/assess/analyze'
      fullPath: '/assess/analyze'
      preLoaderRoute: typeof AssessAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessAnalyzeRoute: AssessAnalyzeRoute,
  AssessChecklistRoute: AssessChecklistRoute,
  AssessPropertyRoute: AssessPropertyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
