/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MisReportesRouteImport } from './routes/mis-reportes'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoluntariosIndexRouteImport } from './routes/voluntarios.index'
import { Route as AssessPropertyRouteImport } from './routes/assess/property'
import { Route as AssessChecklistRouteImport } from './routes/assess/checklist'
import { Route as AssessAnalyzeRouteImport } from './routes/assess/analyze'
import { Route as AdminVoluntariosRouteImport } from './routes/admin.voluntarios'
import { Route as APublicIdRouteImport } from './routes/a/$publicId'
import { Route as VoluntariosPanelTokenRouteImport } from './routes/voluntarios.panel.$token'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const MisReportesRoute = MisReportesRouteImport.update({
  id: '/mis-reportes',
  path: '/mis-reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoluntariosIndexRoute = VoluntariosIndexRouteImport.update({
  id: '/voluntarios/',
  path: '/voluntarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessPropertyRoute = AssessPropertyRouteImport.update({
  id: '/assess/property',
  path: '/assess/property',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessChecklistRoute = AssessChecklistRouteImport.update({
  id: '/assess/checklist',
  path: '/assess/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessAnalyzeRoute = AssessAnalyzeRouteImport.update({
  id: '/assess/analyze',
  path: '/assess/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVoluntariosRoute = AdminVoluntariosRouteImport.update({
  id: '/admin/voluntarios',
  path: '/admin/voluntarios',
  getParentRoute: () => rootRouteImport,
} as any)
const APublicIdRoute = APublicIdRouteImport.update({
  id: '/a/$publicId',
  path: '/a/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const VoluntariosPanelTokenRoute = VoluntariosPanelTokenRouteImport.update({
  id: '/voluntarios/panel/$token',
  path: '/voluntarios/panel/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/metodologia': typeof MetodologiaRoute
  '/mis-reportes': typeof MisReportesRoute
  '/a/$publicId': typeof APublicIdRoute
  '/admin/voluntarios': typeof AdminVoluntariosRoute
  '/assess/analyze': typeof AssessAnalyzeRoute
  '/assess/checklist': typeof AssessChecklistRoute
  '/assess/property': typeof AssessPropertyRoute
  '/voluntarios/': typeof VoluntariosIndexRoute
  '/voluntarios/panel/$token': typeof VoluntariosPanelTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/metodologia': typeof MetodologiaRoute
  '/mis-reportes': typeof MisReportesRoute
  '/a/$publicId': typeof APublicIdRoute
  '/admin/voluntarios': typeof AdminVoluntariosRoute
  '/assess/analyze': typeof AssessAnalyzeRoute
  '/assess/checklist': typeof AssessChecklistRoute
  '/assess/property': typeof AssessPropertyRoute
  '/voluntarios': typeof VoluntariosIndexRoute
  '/voluntarios/panel/$token': typeof VoluntariosPanelTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/metodologia': typeof MetodologiaRoute
  '/mis-reportes': typeof MisReportesRoute
  '/a/$publicId': typeof APublicIdRoute
  '/admin/voluntarios': typeof AdminVoluntariosRoute
  '/assess/analyze': typeof AssessAnalyzeRoute
  '/assess/checklist': typeof AssessChecklistRoute
  '/assess/property': typeof AssessPropertyRoute
  '/voluntarios/': typeof VoluntariosIndexRoute
  '/voluntarios/panel/$token': typeof VoluntariosPanelTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mapa'
    | '/metodologia'
    | '/mis-reportes'
    | '/a/$publicId'
    | '/admin/voluntarios'
    | '/assess/analyze'
    | '/assess/checklist'
    | '/assess/property'
    | '/voluntarios/'
    | '/voluntarios/panel/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mapa'
    | '/metodologia'
    | '/mis-reportes'
    | '/a/$publicId'
    | '/admin/voluntarios'
    | '/assess/analyze'
    | '/assess/checklist'
    | '/assess/property'
    | '/voluntarios'
    | '/voluntarios/panel/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/mapa'
    | '/metodologia'
    | '/mis-reportes'
    | '/a/$publicId'
    | '/admin/voluntarios'
    | '/assess/analyze'
    | '/assess/checklist'
    | '/assess/property'
    | '/voluntarios/'
    | '/voluntarios/panel/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapaRoute: typeof MapaRoute
  MetodologiaRoute: typeof MetodologiaRoute
  MisReportesRoute: typeof MisReportesRoute
  APublicIdRoute: typeof APublicIdRoute
  AdminVoluntariosRoute: typeof AdminVoluntariosRoute
  AssessAnalyzeRoute: typeof AssessAnalyzeRoute
  AssessChecklistRoute: typeof AssessChecklistRoute
  AssessPropertyRoute: typeof AssessPropertyRoute
  VoluntariosIndexRoute: typeof VoluntariosIndexRoute
  VoluntariosPanelTokenRoute: typeof VoluntariosPanelTokenRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mis-reportes': {
      id: '/mis-reportes'
      path: '/mis-reportes'
      fullPath: '/mis-reportes'
      preLoaderRoute: typeof MisReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voluntarios/': {
      id: '/voluntarios/'
      path: '/voluntarios'
      fullPath: '/voluntarios/'
      preLoaderRoute: typeof VoluntariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/property': {
      id: '/assess/property'
      path: '/assess/property'
      fullPath: '/assess/property'
      preLoaderRoute: typeof AssessPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/checklist': {
      id: '/assess/checklist'
      path: '/assess/checklist'
      fullPath: '/assess/checklist'
      preLoaderRoute: typeof AssessChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/analyze': {
      id: '/assess/analyze'
      path: '/assess/analyze'
      fullPath: '/assess/analyze'
      preLoaderRoute: typeof AssessAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/voluntarios': {
      id: '/admin/voluntarios'
      path: '/admin/voluntarios'
      fullPath: '/admin/voluntarios'
      preLoaderRoute: typeof AdminVoluntariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$publicId': {
      id: '/a/$publicId'
      path: '/a/$publicId'
      fullPath: '/a/$publicId'
      preLoaderRoute: typeof APublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voluntarios/panel/$token': {
      id: '/voluntarios/panel/$token'
      path: '/voluntarios/panel/$token'
      fullPath: '/voluntarios/panel/$token'
      preLoaderRoute: typeof VoluntariosPanelTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapaRoute: MapaRoute,
  MetodologiaRoute: MetodologiaRoute,
  MisReportesRoute: MisReportesRoute,
  APublicIdRoute: APublicIdRoute,
  AdminVoluntariosRoute: AdminVoluntariosRoute,
  AssessAnalyzeRoute: AssessAnalyzeRoute,
  AssessChecklistRoute: AssessChecklistRoute,
  AssessPropertyRoute: AssessPropertyRoute,
  VoluntariosIndexRoute: VoluntariosIndexRoute,
  VoluntariosPanelTokenRoute: VoluntariosPanelTokenRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
