/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TembloEnVenezuelaHoyRouteImport } from './routes/temblo-en-venezuela-hoy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as MisReportesRouteImport } from './routes/mis-reportes'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as EarthquakeInVenezuelaTodayRouteImport } from './routes/earthquake-in-venezuela-today'
import { Route as DatosRouteImport } from './routes/datos'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoluntariosIndexRouteImport } from './routes/voluntarios.index'
import { Route as GuiaIndexRouteImport } from './routes/guia.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ZonaEstadoRouteImport } from './routes/zona.$estado'
import { Route as GuiaQueHacerDespuesDeUnTemblorRouteImport } from './routes/guia.que-hacer-despues-de-un-temblor'
import { Route as GuiaGrietasPeligrosasDespuesDeUnSismoRouteImport } from './routes/guia.grietas-peligrosas-despues-de-un-sismo'
import { Route as GuiaFunvisisQueEsYComoFuncionaRouteImport } from './routes/guia.funvisis-que-es-y-como-funciona'
import { Route as GuiaFallaDeBoconoRouteImport } from './routes/guia.falla-de-bocono'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AssessPropertyRouteImport } from './routes/assess/property'
import { Route as AssessChecklistRouteImport } from './routes/assess/checklist'
import { Route as AssessAnalyzeRouteImport } from './routes/assess/analyze'
import { Route as AdminVoluntariosRouteImport } from './routes/admin.voluntarios'
import { Route as APublicIdRouteImport } from './routes/a/$publicId'
import { Route as ZonaEstadoMunicipioRouteImport } from './routes/zona.$estado.$municipio'
import { Route as VoluntariosPanelTokenRouteImport } from './routes/voluntarios.panel.$token'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableCronFunnelAlertRouteImport } from './routes/lovable/cron/funnel-alert'
import { Route as LovableCronEngineerDigestRouteImport } from './routes/lovable/cron/engineer-digest'
import { Route as LovableCronCompletionEngineRouteImport } from './routes/lovable/cron/completion-engine'
import { Route as LovableCronAdminHelpDigestRouteImport } from './routes/lovable/cron/admin-help-digest'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicV1TotalsDotjsonRouteImport } from './routes/api/public/v1/totals[.]json'
import { Route as ApiPublicV1TimeseriesDotjsonRouteImport } from './routes/api/public/v1/timeseries[.]json'
import { Route as ApiPublicV1RiskFactorsDotjsonRouteImport } from './routes/api/public/v1/risk-factors[.]json'
import { Route as ApiPublicV1MethodologyDotjsonRouteImport } from './routes/api/public/v1/methodology[.]json'
import { Route as ApiPublicV1IndexDotjsonRouteImport } from './routes/api/public/v1/index[.]json'
import { Route as ApiPublicV1AggregatesDotjsonRouteImport } from './routes/api/public/v1/aggregates[.]json'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TembloEnVenezuelaHoyRoute = TembloEnVenezuelaHoyRouteImport.update({
  id: '/temblo-en-venezuela-hoy',
  path: '/temblo-en-venezuela-hoy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const MisReportesRoute = MisReportesRouteImport.update({
  id: '/mis-reportes',
  path: '/mis-reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EarthquakeInVenezuelaTodayRoute =
  EarthquakeInVenezuelaTodayRouteImport.update({
    id: '/earthquake-in-venezuela-today',
    path: '/earthquake-in-venezuela-today',
    getParentRoute: () => rootRouteImport,
  } as any)
const DatosRoute = DatosRouteImport.update({
  id: '/datos',
  path: '/datos',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoluntariosIndexRoute = VoluntariosIndexRouteImport.update({
  id: '/voluntarios/',
  path: '/voluntarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaIndexRoute = GuiaIndexRouteImport.update({
  id: '/guia/',
  path: '/guia/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonaEstadoRoute = ZonaEstadoRouteImport.update({
  id: '/zona/$estado',
  path: '/zona/$estado',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaQueHacerDespuesDeUnTemblorRoute =
  GuiaQueHacerDespuesDeUnTemblorRouteImport.update({
    id: '/guia/que-hacer-despues-de-un-temblor',
    path: '/guia/que-hacer-despues-de-un-temblor',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuiaGrietasPeligrosasDespuesDeUnSismoRoute =
  GuiaGrietasPeligrosasDespuesDeUnSismoRouteImport.update({
    id: '/guia/grietas-peligrosas-despues-de-un-sismo',
    path: '/guia/grietas-peligrosas-despues-de-un-sismo',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuiaFunvisisQueEsYComoFuncionaRoute =
  GuiaFunvisisQueEsYComoFuncionaRouteImport.update({
    id: '/guia/funvisis-que-es-y-como-funciona',
    path: '/guia/funvisis-que-es-y-como-funciona',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuiaFallaDeBoconoRoute = GuiaFallaDeBoconoRouteImport.update({
  id: '/guia/falla-de-bocono',
  path: '/guia/falla-de-bocono',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessPropertyRoute = AssessPropertyRouteImport.update({
  id: '/assess/property',
  path: '/assess/property',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessChecklistRoute = AssessChecklistRouteImport.update({
  id: '/assess/checklist',
  path: '/assess/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessAnalyzeRoute = AssessAnalyzeRouteImport.update({
  id: '/assess/analyze',
  path: '/assess/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVoluntariosRoute = AdminVoluntariosRouteImport.update({
  id: '/admin/voluntarios',
  path: '/admin/voluntarios',
  getParentRoute: () => rootRouteImport,
} as any)
const APublicIdRoute = APublicIdRouteImport.update({
  id: '/a/$publicId',
  path: '/a/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonaEstadoMunicipioRoute = ZonaEstadoMunicipioRouteImport.update({
  id: '/$municipio',
  path: '/$municipio',
  getParentRoute: () => ZonaEstadoRoute,
} as any)
const VoluntariosPanelTokenRoute = VoluntariosPanelTokenRouteImport.update({
  id: '/voluntarios/panel/$token',
  path: '/voluntarios/panel/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableCronFunnelAlertRoute = LovableCronFunnelAlertRouteImport.update({
  id: '/lovable/cron/funnel-alert',
  path: '/lovable/cron/funnel-alert',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableCronEngineerDigestRoute =
  LovableCronEngineerDigestRouteImport.update({
    id: '/lovable/cron/engineer-digest',
    path: '/lovable/cron/engineer-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableCronCompletionEngineRoute =
  LovableCronCompletionEngineRouteImport.update({
    id: '/lovable/cron/completion-engine',
    path: '/lovable/cron/completion-engine',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableCronAdminHelpDigestRoute =
  LovableCronAdminHelpDigestRouteImport.update({
    id: '/lovable/cron/admin-help-digest',
    path: '/lovable/cron/admin-help-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1TotalsDotjsonRoute =
  ApiPublicV1TotalsDotjsonRouteImport.update({
    id: '/api/public/v1/totals.json',
    path: '/api/public/v1/totals.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1TimeseriesDotjsonRoute =
  ApiPublicV1TimeseriesDotjsonRouteImport.update({
    id: '/api/public/v1/timeseries.json',
    path: '/api/public/v1/timeseries.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1RiskFactorsDotjsonRoute =
  ApiPublicV1RiskFactorsDotjsonRouteImport.update({
    id: '/api/public/v1/risk-factors.json',
    path: '/api/public/v1/risk-factors.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1MethodologyDotjsonRoute =
  ApiPublicV1MethodologyDotjsonRouteImport.update({
    id: '/api/public/v1/methodology.json',
    path: '/api/public/v1/methodology.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1IndexDotjsonRoute = ApiPublicV1IndexDotjsonRouteImport.update({
  id: '/api/public/v1/index.json',
  path: '/api/public/v1/index.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AggregatesDotjsonRoute =
  ApiPublicV1AggregatesDotjsonRouteImport.update({
    id: '/api/public/v1/aggregates.json',
    path: '/api/public/v1/aggregates.json',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/datos': typeof DatosRoute
  '/earthquake-in-venezuela-today': typeof EarthquakeInVenezuelaTodayRoute
  '/feedback': typeof FeedbackRoute
  '/legal': typeof LegalRoute
  '/mapa': typeof MapaRoute
  '/metodologia': typeof MetodologiaRoute
  '/mis-reportes': typeof MisReportesRoute
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temblo-en-venezuela-hoy': typeof TembloEnVenezuelaHoyRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/a/$publicId': typeof APublicIdRoute
  '/admin/voluntarios': typeof AdminVoluntariosRoute
  '/assess/analyze': typeof AssessAnalyzeRoute
  '/assess/checklist': typeof AssessChecklistRoute
  '/assess/property': typeof AssessPropertyRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guia/falla-de-bocono': typeof GuiaFallaDeBoconoRoute
  '/guia/funvisis-que-es-y-como-funciona': typeof GuiaFunvisisQueEsYComoFuncionaRoute
  '/guia/grietas-peligrosas-despues-de-un-sismo': typeof GuiaGrietasPeligrosasDespuesDeUnSismoRoute
  '/guia/que-hacer-despues-de-un-temblor': typeof GuiaQueHacerDespuesDeUnTemblorRoute
  '/zona/$estado': typeof ZonaEstadoRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/guia/': typeof GuiaIndexRoute
  '/voluntarios/': typeof VoluntariosIndexRoute
  '/lovable/cron/admin-help-digest': typeof LovableCronAdminHelpDigestRoute
  '/lovable/cron/completion-engine': typeof LovableCronCompletionEngineRoute
  '/lovable/cron/engineer-digest': typeof LovableCronEngineerDigestRoute
  '/lovable/cron/funnel-alert': typeof LovableCronFunnelAlertRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/voluntarios/panel/$token': typeof VoluntariosPanelTokenRoute
  '/zona/$estado/$municipio': typeof ZonaEstadoMunicipioRoute
  '/api/public/v1/aggregates.json': typeof ApiPublicV1AggregatesDotjsonRoute
  '/api/public/v1/index.json': typeof ApiPublicV1IndexDotjsonRoute
  '/api/public/v1/methodology.json': typeof ApiPublicV1MethodologyDotjsonRoute
  '/api/public/v1/risk-factors.json': typeof ApiPublicV1RiskFactorsDotjsonRoute
  '/api/public/v1/timeseries.json': typeof ApiPublicV1TimeseriesDotjsonRoute
  '/api/public/v1/totals.json': typeof ApiPublicV1TotalsDotjsonRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/datos': typeof DatosRoute
  '/earthquake-in-venezuela-today': typeof EarthquakeInVenezuelaTodayRoute
  '/feedback': typeof FeedbackRoute
  '/legal': typeof LegalRoute
  '/mapa': typeof MapaRoute
  '/metodologia': typeof MetodologiaRoute
  '/mis-reportes': typeof MisReportesRoute
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temblo-en-venezuela-hoy': typeof TembloEnVenezuelaHoyRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/a/$publicId': typeof APublicIdRoute
  '/admin/voluntarios': typeof AdminVoluntariosRoute
  '/assess/analyze': typeof AssessAnalyzeRoute
  '/assess/checklist': typeof AssessChecklistRoute
  '/assess/property': typeof AssessPropertyRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guia/falla-de-bocono': typeof GuiaFallaDeBoconoRoute
  '/guia/funvisis-que-es-y-como-funciona': typeof GuiaFunvisisQueEsYComoFuncionaRoute
  '/guia/grietas-peligrosas-despues-de-un-sismo': typeof GuiaGrietasPeligrosasDespuesDeUnSismoRoute
  '/guia/que-hacer-despues-de-un-temblor': typeof GuiaQueHacerDespuesDeUnTemblorRoute
  '/zona/$estado': typeof ZonaEstadoRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/guia': typeof GuiaIndexRoute
  '/voluntarios': typeof VoluntariosIndexRoute
  '/lovable/cron/admin-help-digest': typeof LovableCronAdminHelpDigestRoute
  '/lovable/cron/completion-engine': typeof LovableCronCompletionEngineRoute
  '/lovable/cron/engineer-digest': typeof LovableCronEngineerDigestRoute
  '/lovable/cron/funnel-alert': typeof LovableCronFunnelAlertRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/voluntarios/panel/$token': typeof VoluntariosPanelTokenRoute
  '/zona/$estado/$municipio': typeof ZonaEstadoMunicipioRoute
  '/api/public/v1/aggregates.json': typeof ApiPublicV1AggregatesDotjsonRoute
  '/api/public/v1/index.json': typeof ApiPublicV1IndexDotjsonRoute
  '/api/public/v1/methodology.json': typeof ApiPublicV1MethodologyDotjsonRoute
  '/api/public/v1/risk-factors.json': typeof ApiPublicV1RiskFactorsDotjsonRoute
  '/api/public/v1/timeseries.json': typeof ApiPublicV1TimeseriesDotjsonRoute
  '/api/public/v1/totals.json': typeof ApiPublicV1TotalsDotjsonRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/datos': typeof DatosRoute
  '/earthquake-in-venezuela-today': typeof EarthquakeInVenezuelaTodayRoute
  '/feedback': typeof FeedbackRoute
  '/legal': typeof LegalRoute
  '/mapa': typeof MapaRoute
  '/metodologia': typeof MetodologiaRoute
  '/mis-reportes': typeof MisReportesRoute
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temblo-en-venezuela-hoy': typeof TembloEnVenezuelaHoyRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/a/$publicId': typeof APublicIdRoute
  '/admin/voluntarios': typeof AdminVoluntariosRoute
  '/assess/analyze': typeof AssessAnalyzeRoute
  '/assess/checklist': typeof AssessChecklistRoute
  '/assess/property': typeof AssessPropertyRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guia/falla-de-bocono': typeof GuiaFallaDeBoconoRoute
  '/guia/funvisis-que-es-y-como-funciona': typeof GuiaFunvisisQueEsYComoFuncionaRoute
  '/guia/grietas-peligrosas-despues-de-un-sismo': typeof GuiaGrietasPeligrosasDespuesDeUnSismoRoute
  '/guia/que-hacer-despues-de-un-temblor': typeof GuiaQueHacerDespuesDeUnTemblorRoute
  '/zona/$estado': typeof ZonaEstadoRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/guia/': typeof GuiaIndexRoute
  '/voluntarios/': typeof VoluntariosIndexRoute
  '/lovable/cron/admin-help-digest': typeof LovableCronAdminHelpDigestRoute
  '/lovable/cron/completion-engine': typeof LovableCronCompletionEngineRoute
  '/lovable/cron/engineer-digest': typeof LovableCronEngineerDigestRoute
  '/lovable/cron/funnel-alert': typeof LovableCronFunnelAlertRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/voluntarios/panel/$token': typeof VoluntariosPanelTokenRoute
  '/zona/$estado/$municipio': typeof ZonaEstadoMunicipioRoute
  '/api/public/v1/aggregates.json': typeof ApiPublicV1AggregatesDotjsonRoute
  '/api/public/v1/index.json': typeof ApiPublicV1IndexDotjsonRoute
  '/api/public/v1/methodology.json': typeof ApiPublicV1MethodologyDotjsonRoute
  '/api/public/v1/risk-factors.json': typeof ApiPublicV1RiskFactorsDotjsonRoute
  '/api/public/v1/timeseries.json': typeof ApiPublicV1TimeseriesDotjsonRoute
  '/api/public/v1/totals.json': typeof ApiPublicV1TotalsDotjsonRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ayuda'
    | '/datos'
    | '/earthquake-in-venezuela-today'
    | '/feedback'
    | '/legal'
    | '/mapa'
    | '/metodologia'
    | '/mis-reportes'
    | '/privacidad'
    | '/sitemap.xml'
    | '/temblo-en-venezuela-hoy'
    | '/unsubscribe'
    | '/a/$publicId'
    | '/admin/voluntarios'
    | '/assess/analyze'
    | '/assess/checklist'
    | '/assess/property'
    | '/email/unsubscribe'
    | '/guia/falla-de-bocono'
    | '/guia/funvisis-que-es-y-como-funciona'
    | '/guia/grietas-peligrosas-despues-de-un-sismo'
    | '/guia/que-hacer-despues-de-un-temblor'
    | '/zona/$estado'
    | '/admin/'
    | '/guia/'
    | '/voluntarios/'
    | '/lovable/cron/admin-help-digest'
    | '/lovable/cron/completion-engine'
    | '/lovable/cron/engineer-digest'
    | '/lovable/cron/funnel-alert'
    | '/lovable/email/suppression'
    | '/voluntarios/panel/$token'
    | '/zona/$estado/$municipio'
    | '/api/public/v1/aggregates.json'
    | '/api/public/v1/index.json'
    | '/api/public/v1/methodology.json'
    | '/api/public/v1/risk-factors.json'
    | '/api/public/v1/timeseries.json'
    | '/api/public/v1/totals.json'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ayuda'
    | '/datos'
    | '/earthquake-in-venezuela-today'
    | '/feedback'
    | '/legal'
    | '/mapa'
    | '/metodologia'
    | '/mis-reportes'
    | '/privacidad'
    | '/sitemap.xml'
    | '/temblo-en-venezuela-hoy'
    | '/unsubscribe'
    | '/a/$publicId'
    | '/admin/voluntarios'
    | '/assess/analyze'
    | '/assess/checklist'
    | '/assess/property'
    | '/email/unsubscribe'
    | '/guia/falla-de-bocono'
    | '/guia/funvisis-que-es-y-como-funciona'
    | '/guia/grietas-peligrosas-despues-de-un-sismo'
    | '/guia/que-hacer-despues-de-un-temblor'
    | '/zona/$estado'
    | '/admin'
    | '/guia'
    | '/voluntarios'
    | '/lovable/cron/admin-help-digest'
    | '/lovable/cron/completion-engine'
    | '/lovable/cron/engineer-digest'
    | '/lovable/cron/funnel-alert'
    | '/lovable/email/suppression'
    | '/voluntarios/panel/$token'
    | '/zona/$estado/$municipio'
    | '/api/public/v1/aggregates.json'
    | '/api/public/v1/index.json'
    | '/api/public/v1/methodology.json'
    | '/api/public/v1/risk-factors.json'
    | '/api/public/v1/timeseries.json'
    | '/api/public/v1/totals.json'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/ayuda'
    | '/datos'
    | '/earthquake-in-venezuela-today'
    | '/feedback'
    | '/legal'
    | '/mapa'
    | '/metodologia'
    | '/mis-reportes'
    | '/privacidad'
    | '/sitemap.xml'
    | '/temblo-en-venezuela-hoy'
    | '/unsubscribe'
    | '/a/$publicId'
    | '/admin/voluntarios'
    | '/assess/analyze'
    | '/assess/checklist'
    | '/assess/property'
    | '/email/unsubscribe'
    | '/guia/falla-de-bocono'
    | '/guia/funvisis-que-es-y-como-funciona'
    | '/guia/grietas-peligrosas-despues-de-un-sismo'
    | '/guia/que-hacer-despues-de-un-temblor'
    | '/zona/$estado'
    | '/admin/'
    | '/guia/'
    | '/voluntarios/'
    | '/lovable/cron/admin-help-digest'
    | '/lovable/cron/completion-engine'
    | '/lovable/cron/engineer-digest'
    | '/lovable/cron/funnel-alert'
    | '/lovable/email/suppression'
    | '/voluntarios/panel/$token'
    | '/zona/$estado/$municipio'
    | '/api/public/v1/aggregates.json'
    | '/api/public/v1/index.json'
    | '/api/public/v1/methodology.json'
    | '/api/public/v1/risk-factors.json'
    | '/api/public/v1/timeseries.json'
    | '/api/public/v1/totals.json'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AyudaRoute: typeof AyudaRoute
  DatosRoute: typeof DatosRoute
  EarthquakeInVenezuelaTodayRoute: typeof EarthquakeInVenezuelaTodayRoute
  FeedbackRoute: typeof FeedbackRoute
  LegalRoute: typeof LegalRoute
  MapaRoute: typeof MapaRoute
  MetodologiaRoute: typeof MetodologiaRoute
  MisReportesRoute: typeof MisReportesRoute
  PrivacidadRoute: typeof PrivacidadRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TembloEnVenezuelaHoyRoute: typeof TembloEnVenezuelaHoyRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  APublicIdRoute: typeof APublicIdRoute
  AdminVoluntariosRoute: typeof AdminVoluntariosRoute
  AssessAnalyzeRoute: typeof AssessAnalyzeRoute
  AssessChecklistRoute: typeof AssessChecklistRoute
  AssessPropertyRoute: typeof AssessPropertyRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  GuiaFallaDeBoconoRoute: typeof GuiaFallaDeBoconoRoute
  GuiaFunvisisQueEsYComoFuncionaRoute: typeof GuiaFunvisisQueEsYComoFuncionaRoute
  GuiaGrietasPeligrosasDespuesDeUnSismoRoute: typeof GuiaGrietasPeligrosasDespuesDeUnSismoRoute
  GuiaQueHacerDespuesDeUnTemblorRoute: typeof GuiaQueHacerDespuesDeUnTemblorRoute
  ZonaEstadoRoute: typeof ZonaEstadoRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  GuiaIndexRoute: typeof GuiaIndexRoute
  VoluntariosIndexRoute: typeof VoluntariosIndexRoute
  LovableCronAdminHelpDigestRoute: typeof LovableCronAdminHelpDigestRoute
  LovableCronCompletionEngineRoute: typeof LovableCronCompletionEngineRoute
  LovableCronEngineerDigestRoute: typeof LovableCronEngineerDigestRoute
  LovableCronFunnelAlertRoute: typeof LovableCronFunnelAlertRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  VoluntariosPanelTokenRoute: typeof VoluntariosPanelTokenRoute
  ApiPublicV1AggregatesDotjsonRoute: typeof ApiPublicV1AggregatesDotjsonRoute
  ApiPublicV1IndexDotjsonRoute: typeof ApiPublicV1IndexDotjsonRoute
  ApiPublicV1MethodologyDotjsonRoute: typeof ApiPublicV1MethodologyDotjsonRoute
  ApiPublicV1RiskFactorsDotjsonRoute: typeof ApiPublicV1RiskFactorsDotjsonRoute
  ApiPublicV1TimeseriesDotjsonRoute: typeof ApiPublicV1TimeseriesDotjsonRoute
  ApiPublicV1TotalsDotjsonRoute: typeof ApiPublicV1TotalsDotjsonRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temblo-en-venezuela-hoy': {
      id: '/temblo-en-venezuela-hoy'
      path: '/temblo-en-venezuela-hoy'
      fullPath: '/temblo-en-venezuela-hoy'
      preLoaderRoute: typeof TembloEnVenezuelaHoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-reportes': {
      id: '/mis-reportes'
      path: '/mis-reportes'
      fullPath: '/mis-reportes'
      preLoaderRoute: typeof MisReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earthquake-in-venezuela-today': {
      id: '/earthquake-in-venezuela-today'
      path: '/earthquake-in-venezuela-today'
      fullPath: '/earthquake-in-venezuela-today'
      preLoaderRoute: typeof EarthquakeInVenezuelaTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datos': {
      id: '/datos'
      path: '/datos'
      fullPath: '/datos'
      preLoaderRoute: typeof DatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voluntarios/': {
      id: '/voluntarios/'
      path: '/voluntarios'
      fullPath: '/voluntarios/'
      preLoaderRoute: typeof VoluntariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/': {
      id: '/guia/'
      path: '/guia'
      fullPath: '/guia/'
      preLoaderRoute: typeof GuiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zona/$estado': {
      id: '/zona/$estado'
      path: '/zona/$estado'
      fullPath: '/zona/$estado'
      preLoaderRoute: typeof ZonaEstadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/que-hacer-despues-de-un-temblor': {
      id: '/guia/que-hacer-despues-de-un-temblor'
      path: '/guia/que-hacer-despues-de-un-temblor'
      fullPath: '/guia/que-hacer-despues-de-un-temblor'
      preLoaderRoute: typeof GuiaQueHacerDespuesDeUnTemblorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/grietas-peligrosas-despues-de-un-sismo': {
      id: '/guia/grietas-peligrosas-despues-de-un-sismo'
      path: '/guia/grietas-peligrosas-despues-de-un-sismo'
      fullPath: '/guia/grietas-peligrosas-despues-de-un-sismo'
      preLoaderRoute: typeof GuiaGrietasPeligrosasDespuesDeUnSismoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/funvisis-que-es-y-como-funciona': {
      id: '/guia/funvisis-que-es-y-como-funciona'
      path: '/guia/funvisis-que-es-y-como-funciona'
      fullPath: '/guia/funvisis-que-es-y-como-funciona'
      preLoaderRoute: typeof GuiaFunvisisQueEsYComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/falla-de-bocono': {
      id: '/guia/falla-de-bocono'
      path: '/guia/falla-de-bocono'
      fullPath: '/guia/falla-de-bocono'
      preLoaderRoute: typeof GuiaFallaDeBoconoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/property': {
      id: '/assess/property'
      path: '/assess/property'
      fullPath: '/assess/property'
      preLoaderRoute: typeof AssessPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/checklist': {
      id: '/assess/checklist'
      path: '/assess/checklist'
      fullPath: '/assess/checklist'
      preLoaderRoute: typeof AssessChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/analyze': {
      id: '/assess/analyze'
      path: '/assess/analyze'
      fullPath: '/assess/analyze'
      preLoaderRoute: typeof AssessAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/voluntarios': {
      id: '/admin/voluntarios'
      path: '/admin/voluntarios'
      fullPath: '/admin/voluntarios'
      preLoaderRoute: typeof AdminVoluntariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$publicId': {
      id: '/a/$publicId'
      path: '/a/$publicId'
      fullPath: '/a/$publicId'
      preLoaderRoute: typeof APublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zona/$estado/$municipio': {
      id: '/zona/$estado/$municipio'
      path: '/$municipio'
      fullPath: '/zona/$estado/$municipio'
      preLoaderRoute: typeof ZonaEstadoMunicipioRouteImport
      parentRoute: typeof ZonaEstadoRoute
    }
    '/voluntarios/panel/$token': {
      id: '/voluntarios/panel/$token'
      path: '/voluntarios/panel/$token'
      fullPath: '/voluntarios/panel/$token'
      preLoaderRoute: typeof VoluntariosPanelTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/cron/funnel-alert': {
      id: '/lovable/cron/funnel-alert'
      path: '/lovable/cron/funnel-alert'
      fullPath: '/lovable/cron/funnel-alert'
      preLoaderRoute: typeof LovableCronFunnelAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/cron/engineer-digest': {
      id: '/lovable/cron/engineer-digest'
      path: '/lovable/cron/engineer-digest'
      fullPath: '/lovable/cron/engineer-digest'
      preLoaderRoute: typeof LovableCronEngineerDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/cron/completion-engine': {
      id: '/lovable/cron/completion-engine'
      path: '/lovable/cron/completion-engine'
      fullPath: '/lovable/cron/completion-engine'
      preLoaderRoute: typeof LovableCronCompletionEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/cron/admin-help-digest': {
      id: '/lovable/cron/admin-help-digest'
      path: '/lovable/cron/admin-help-digest'
      fullPath: '/lovable/cron/admin-help-digest'
      preLoaderRoute: typeof LovableCronAdminHelpDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/totals.json': {
      id: '/api/public/v1/totals.json'
      path: '/api/public/v1/totals.json'
      fullPath: '/api/public/v1/totals.json'
      preLoaderRoute: typeof ApiPublicV1TotalsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/timeseries.json': {
      id: '/api/public/v1/timeseries.json'
      path: '/api/public/v1/timeseries.json'
      fullPath: '/api/public/v1/timeseries.json'
      preLoaderRoute: typeof ApiPublicV1TimeseriesDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/risk-factors.json': {
      id: '/api/public/v1/risk-factors.json'
      path: '/api/public/v1/risk-factors.json'
      fullPath: '/api/public/v1/risk-factors.json'
      preLoaderRoute: typeof ApiPublicV1RiskFactorsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/methodology.json': {
      id: '/api/public/v1/methodology.json'
      path: '/api/public/v1/methodology.json'
      fullPath: '/api/public/v1/methodology.json'
      preLoaderRoute: typeof ApiPublicV1MethodologyDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/index.json': {
      id: '/api/public/v1/index.json'
      path: '/api/public/v1/index.json'
      fullPath: '/api/public/v1/index.json'
      preLoaderRoute: typeof ApiPublicV1IndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/aggregates.json': {
      id: '/api/public/v1/aggregates.json'
      path: '/api/public/v1/aggregates.json'
      fullPath: '/api/public/v1/aggregates.json'
      preLoaderRoute: typeof ApiPublicV1AggregatesDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ZonaEstadoRouteChildren {
  ZonaEstadoMunicipioRoute: typeof ZonaEstadoMunicipioRoute
}

const ZonaEstadoRouteChildren: ZonaEstadoRouteChildren = {
  ZonaEstadoMunicipioRoute: ZonaEstadoMunicipioRoute,
}

const ZonaEstadoRouteWithChildren = ZonaEstadoRoute._addFileChildren(
  ZonaEstadoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AyudaRoute: AyudaRoute,
  DatosRoute: DatosRoute,
  EarthquakeInVenezuelaTodayRoute: EarthquakeInVenezuelaTodayRoute,
  FeedbackRoute: FeedbackRoute,
  LegalRoute: LegalRoute,
  MapaRoute: MapaRoute,
  MetodologiaRoute: MetodologiaRoute,
  MisReportesRoute: MisReportesRoute,
  PrivacidadRoute: PrivacidadRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TembloEnVenezuelaHoyRoute: TembloEnVenezuelaHoyRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  APublicIdRoute: APublicIdRoute,
  AdminVoluntariosRoute: AdminVoluntariosRoute,
  AssessAnalyzeRoute: AssessAnalyzeRoute,
  AssessChecklistRoute: AssessChecklistRoute,
  AssessPropertyRoute: AssessPropertyRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  GuiaFallaDeBoconoRoute: GuiaFallaDeBoconoRoute,
  GuiaFunvisisQueEsYComoFuncionaRoute: GuiaFunvisisQueEsYComoFuncionaRoute,
  GuiaGrietasPeligrosasDespuesDeUnSismoRoute:
    GuiaGrietasPeligrosasDespuesDeUnSismoRoute,
  GuiaQueHacerDespuesDeUnTemblorRoute: GuiaQueHacerDespuesDeUnTemblorRoute,
  ZonaEstadoRoute: ZonaEstadoRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  GuiaIndexRoute: GuiaIndexRoute,
  VoluntariosIndexRoute: VoluntariosIndexRoute,
  LovableCronAdminHelpDigestRoute: LovableCronAdminHelpDigestRoute,
  LovableCronCompletionEngineRoute: LovableCronCompletionEngineRoute,
  LovableCronEngineerDigestRoute: LovableCronEngineerDigestRoute,
  LovableCronFunnelAlertRoute: LovableCronFunnelAlertRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  VoluntariosPanelTokenRoute: VoluntariosPanelTokenRoute,
  ApiPublicV1AggregatesDotjsonRoute: ApiPublicV1AggregatesDotjsonRoute,
  ApiPublicV1IndexDotjsonRoute: ApiPublicV1IndexDotjsonRoute,
  ApiPublicV1MethodologyDotjsonRoute: ApiPublicV1MethodologyDotjsonRoute,
  ApiPublicV1RiskFactorsDotjsonRoute: ApiPublicV1RiskFactorsDotjsonRoute,
  ApiPublicV1TimeseriesDotjsonRoute: ApiPublicV1TimeseriesDotjsonRoute,
  ApiPublicV1TotalsDotjsonRoute: ApiPublicV1TotalsDotjsonRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
